### PR TITLE
using physical threads

### LINKED ISSUE #596: Perfomance loss without `export OMP_NUM_THREADS=1`
Hi,

I am doing some benchmarks on a new laptop and I isolated some particular settings leading to significant performance losses depending on whether `export OMP_NUM_THREADS=1` is used or not before launching Python. Could you please try to reproduce the following? 

### Install FINUFFT in a fresh virtual environment using pip

```bash
# create fresh environment
python3 -m venv ~/.venv/finufft
source ~/.venv/finufft/bin/activate

# install finufft
pip install finufft   
pip install packaging # needed otherwise `import finufft` will fail (this is a bug right?)
```

Notice the comment mentioning a potential missing dependency related to finufft installation with pip (but this is not really what has brought me here).
   
### Benchmarking issue

Open a Python console from the terminal and copy-paste the following.

```python
import numpy as np
import time
import finufft

M = 50000
N1, N2, N3 = 50, 25, 25
dtype = np.float32
nrepeat = 10

# test nufft3d1
for id in range(nrepeat):
    
    # generate nodes
    x = np.linspace(-np.pi, 0., M, dtype=dtype)
    y = np.linspace(-np.pi, np.pi, M, dtype=dtype)
    z = np.linspace(-np.pi, np.pi, M, dtype=dtype)
    c_re = np.linspace(-1, 1, M, dtype=dtype)
    c_im = np.linspace(-1, 1, M, dtype=dtype)
    c = c_re + 1J * c_im
    
    # compute 3D NUFFT (type 1)
    start_cpu = time.perf_counter()
    out = finufft.nufft3d1(x, y, z, c, n_modes=(N1, N2, N3), out=None, eps=1e-5)
    end_cpu = time.perf_counter()
    etime_ms = (end_cpu - start_cpu) * 1000.
    print("pass %d : elapsed time = %g ms" % (id, etime_ms))

```

Here is what I get (it is very slow excepting for pass 1 in this run, the observed execution time can change quite a lot from one pass to another):

```
pass 0 : elapsed time = 7868.64 ms
pass 1 : elapsed time = 17.4045 ms
pass 2 : elapsed time = 7656.45 ms
pass 3 : elapsed time = 7750.34 ms
pass 4 : elapsed time = 7584.46 ms
pass 5 : elapsed time = 7802.8 ms
pass 6 : elapsed time = 7915.14 ms
pass 7 : elapsed time = 2921.09 ms
pass 8 : elapsed time = 3109.38 ms
pass 9 : elapsed time = 6330.15 ms
```

Now open a terminal and type

```bash
export OMP_NUM_THREADS=1
python
```

then copy-paste again the benchmarking code above. Here is what I get (much faster and repeatable execution times):

```
pass 0 : elapsed time = 4.60164 ms
pass 1 : elapsed time = 4.32843 ms
pass 2 : elapsed time = 4.23474 ms
pass 3 : elapsed time = 4.25191 ms
pass 4 : elapsed time = 4.6779 ms
pass 5 : elapsed time = 5.35747 ms
pass 6 : elapsed time = 5.08332 ms
pass 7 : elapsed time = 4.82096 ms
pass 8 : elapsed time = 5.05432 ms
pass 9 : elapsed time = 4.17692 ms
```

### Additional comments

- Without `export OMP_NUM_THREADS=1`, changing `dtype = np.float32` into `dtype = np.float64` drops the computation time to roughly 40ms per pass. 
- The observed behavior seems dependent of the choice of `(N1, N2, N3)`, for instance, `N1 = N2 = N3 = 50` leads to roughly 40ms per pass with `dtype = np.float32` and without  `export OMP_NUM_THREADS=1`.

### Environment

- OS: Ubuntu 24.04.1 LTS
- Python: 3.12.3
- FINUFFT: 2.3.0
- CPU Type: Intel Core i9-13950H  (24 cores HT, 36 Mo cache)
- GPU: NVIDIA RTX 4000 ADA 12Go DDR6

### PR DESCRIPTION
**Pull request by DiamonDinoia**
Attempting to fix #596 

Two main reasons:
 - Vector unit are per physical core. 
 - Manually vectorized code is (also the FFT) are memory bound.

Using HT cores impairs performance due to extra scheduling and puts unnecessary strain onto the memory controller

### CODE REVIEW

File: src/finufft_core.cpp [hunk 1]
```diff
@@ -590,8 +590,8 @@ FINUFFT_PLAN_T<TF>::FINUFFT_PLAN_T(int type_, int dim_, const BIGINT *n_modes, i
 
 #ifdef _OPENMP
   // choose overall # threads...
-  int ompmaxnthr = MY_OMP_GET_MAX_THREADS();
-  int nthr       = ompmaxnthr; // default: use as many as OMP gives us
+  int ompmaxnthr = getPhysicalCoreCount();
+  int nthr       = ompmaxnthr; // default: use as many physical cores as possible
   // (the above could be set, or suggested set, to 1 for small enough problems...)
   if (opts.nthreads > 0) {
     nthr = opts.nthreads; // user override, now without limit
```
Comment (mreineck) [inline src/finufft_core.cpp:597]: (Sorry, I couldn't figure out how to annotate the `fprintf` statement directly...)

The warning statement a few lines below will need adjustment, since we are no longer relying on the number of threads that OpenMP reports as available.

File: src/finufft_utils.cpp [hunk 2]
```diff
@@ -57,6 +70,102 @@ double CNTime::elapsedsec() const
...
+  }
+
+#elif defined(__APPLE__)
+  // Retrieve the number of physical cores using sysctl.
+  int cores   = 0;
+  size_t size = sizeof(cores);
+  if (sysctlbyname("hw.physicalcpu", &cores, &size, nullptr, 0) == 0)
+    physicalCoreCount = static_cast<unsigned int>(cores);
+
+#elif defined(__linux__)
```
Comment (mreineck) [inline src/finufft_utils.cpp:102]: Just a small word of caution: this will always report the full umber of physical cores on the system, independent of possible restrictions on the executable itself. On computing cener nodes, the system may limit a job to a part of the available hardware (e.g. via `taskset`); if this happens, the code here will overestimate the number of usable cores.
On systems with power and efficiency cores the code will probably (this is just speculation, I haven't tested it) return the sum of both core counts, which may also be larger than the amount of cores that should actually be used.

I'm not saying that the code should be changed (I wouldn't know how...), but this could be worth remembering in case there are reports about weird behaviour in the future.

Comment (blackwer) [reply src/finufft_utils.cpp:140]: I was going to suggest looking at `hwloc` for inspiration, and it looks like you've found a very similar solution that they did. For posterity:
https://github.com/open-mpi/hwloc/blob/1779eae26f2f55a510e9d73cb648b68e71d9e6d4/hwloc/topology-linux.c#L1036

Comment (mreineck) [reply src/finufft_utils.cpp:138]: I was going to suggest `libpthreads` ... it seems this functionality is available everywhere these days :-)

Comment (DiamonDinoia) [reply src/finufft_utils.cpp:138]: Where is the functionality in pthread?  I didn't go the route of hwloc because I read somewhere that is an issue on maybe freebsd? This seemed more portable to me

Comment (mreineck) [reply src/finufft_utils.cpp:138]: In `ducc` I'm using
```C++
size_t available_hardware_threads()
  {
  static const size_t available_hardware_threads_ = []()
    {
#if __has_include(<pthread.h>) && defined(__linux__) && defined(_GNU_SOURCE)
    cpu_set_t cpuset;
    CPU_ZERO(&cpuset);
    pthread_getaffinity_np(pthread_self(), sizeof(cpuset), &cpuset);
    size_t res=0;
    for (size_t i=0; i<CPU_SETSIZE; ++i)
      if (CPU_ISSET(i, &cpuset)) ++res;
#else
    size_t res = std::max<size_t>(1, std::thread::hardware_concurrency());
#endif
    return res;
    }();
  return available_hardware_threads_;
  }
```

which is very close to your `getAllowedCoreCount` function, but it gets the affinity masks from `libpthreads` instad of the GNU `libc`. It *might* be more portable, but I'm not sure.
